### ISSUE TITLE
Replace the standard 11 kHz mode with 16 kHz

### ISSUE THREAD

**Issue by DJUnit27** [diracdeltas/spleeter4max#10]
The standard Spleeter algorithm cuts frequiencies harshly over 11 kHz. You can make it split frequencies up to 16kHz by changing "spleeter:4stems" to "spleeter:4stems-16kHz" in line 42 of spleeter.js.

![Screenshot (95)](https://user-images.githubusercontent.com/6503824/82129686-1d3c6600-978a-11ea-984d-148c8e16feb3.png)
![Screenshot (97)](https://user-images.githubusercontent.com/6503824/82129687-1dd4fc80-978a-11ea-8cd9-31212c9e164e.png)

**Comment by diracdeltas** [comment]
@DJUnit27 thanks for opening an issue, i was about to do so. i think i will add it as an option in the next major update. the reason being:

* the models were all trained on 11khz, so the ML part doesn't inherently seem like it'd be better with 16khz
* 16khz seems about 30% slower when i tested it

**Comment by diracdeltas** [comment]
this is done in the latest release on the github releases page
