### ISSUE TITLE
spleeter error: js: can't find file main.js (windows 7)

### ISSUE THREAD

**Issue by Tista17** [diracdeltas/spleeter4max#12]
![image](https://user-images.githubusercontent.com/65473296/82133244-fe000180-97a6-11ea-9eb9-a6934fe1ca4c.png)

**Describe the issue**

**Max Console Screenshots**
Add max console screenshots to help explain your problem. See here for instructions: https://github.com/diracdeltas/spleeter4max#help-its-still-not-working

**Info:**
 - Using spleeter or spleeter-native?
 - OS: [e.g. Windows]
 - Ableton version [e.g. 10.1.9]
 - Max version [e.g. 8.1.2]

**Comment by diracdeltas** [comment]
did you move spleeter.amxd out of the folder that it was in? it needs to stay in the same spleeter/ or spleeter-native/ folder that you downloaded it in. (you can move the folder, but not the device by itself)

**Comment by Tista17** [comment]
I did move it out of the folder. I now copied the whole folder and now get the following error:

![image](https://user-images.githubusercontent.com/65473296/82138835-b4cca380-97e0-11ea-8827-07dadf352392.png)

thank you!

**Comment by diracdeltas** [comment]
@Tista17 are you on max 8.0 or earlier? unfortunately this only works with max 8.1 and above
