### ISSUE TITLE
how to install in macOS. please clear this step by step

### ISSUE THREAD

**Issue by ginni1** [diracdeltas/spleeter4max#13]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by diracdeltas** [comment]
please read everything from https://github.com/diracdeltas/spleeter4max#before-you-start onwards. this covers macos instruction with docker.

if you don't want to use docker, download https://github.com/diracdeltas/spleeter4max/releases/tag/1.3-native instead and read https://github.com/diracdeltas/spleeter4max/blob/feature/native-spleeter/README.md#before-you-start
