### ISSUE TITLE
Command Not Found (but spleeter is symlinked)

### ISSUE THREAD

**Issue by dillonrag** [diracdeltas/spleeter4max#15]
**Description:**
The Max for Live device gives a "bin/sh: command not found" error.

Spleeter is **definitely** symlinked. I can run it from the terminal with no problems (_without_ having to specify the full path to the binary). I just can't run it from within Live as a Max Device.

**Screenshot:**
<img width="933" alt="Screen Shot 2020-05-17 at 5 24 20 PM" src="https://user-images.githubusercontent.com/28658090/82164117-e175cf00-9863-11ea-9d98-d027ad5ea8da.png">

**Info:**
 Using spleeter-native
OS: macOS 10.14.6
Ableton version: 10.1.13
Max version: 8.1.3

**Comment by diracdeltas** [comment]
what's the output of `which spleeter` in terminal?

**Comment by diracdeltas** [comment]
as a quickfix i think you can open spleeter.js locally and replace `spleeter separate ...` in https://github.com/diracdeltas/spleeter4max/blob/feature/native-spleeter/spleeter.js#L42 with `python3 -m spleeter separate ...` (or python if that's what python3.7 is linked to)

**Comment by dillonrag** [comment]
Problem has been resolved! User error.

I had the symlink pointing from the spleeter file in /site-packages instead of /bin (within python3.7). Not sure how I managed to make that mistake.

**Comment by dillonrag** [comment]
Thank you btw, this is amazing!
