### ISSUE TITLE
Where to put the spleeter folder. (Could not run docker) (MAC)

### ISSUE THREAD

**Issue by Bonsaimusic** [diracdeltas/spleeter4max#16]
Hey :)
I have been having a problem running spleeter in Ableton (MAC). 
I know the READ ME says to **"unzip spleeter-native.zip and add the spleeter-native/ folder to your Places menu in Ableton"**. My question is: Where in places should I move the spleeter folder to? If I just add it in Ableton straight out of my downloads folder, it says "Could not run Docker". 

I would really appreciate some help!

Cheers

<img width="163" alt="Screenshot 2020-05-18 at 14 56 43" src="https://user-images.githubusercontent.com/65546531/82216164-d5981480-9918-11ea-8d68-3b52968a2438.png">
<img width="736" alt="Screenshot 2020-05-18 at 15 12 59" src="https://user-images.githubusercontent.com/65546531/82217101-3c69fd80-991a-11ea-8ce6-6ae8a0cc9f1b.png">

**Comment by diracdeltas** [comment]
@Bonsaimusic it looks like you downloaded spleeter but are following the instructions for spleeter-native. if you look at the instructions for spleeter it tells you how to install docker: https://github.com/diracdeltas/spleeter4max#spleeter-for-max
