### ISSUE TITLE
After highlighting clip and pressing start, nothing happens and the start button disappears. On max it says "node.script: no such object"

### ISSUE THREAD

**Issue by julienneby** [diracdeltas/spleeter4max#19]
**Did you read the installation instructions already?** 
If not, read them BEFORE opening an issue. Go to https://github.com/diracdeltas/spleeter4max#before-you-start (spleeter) or https://github.com/diracdeltas/spleeter4max/blob/feature/native-spleeter/README.md#before-you-start (spleeter-native).

**Describe the issue**
A clear description of what problem you are having.

**Max Console Screenshots**
Add max console screenshots to help explain your problem. See here for instructions: https://github.com/diracdeltas/spleeter4max#help-its-still-not-working

<img width="736" alt="Screen Shot 2020-05-19 at 1 32 58 AM" src="https://user-images.githubusercontent.com/65594016/82304692-7e725e00-9971-11ea-9ae3-b100a3ad50fc.png">

**Info:**
 - Using spleeter or spleeter-native? DOWNLOADED DOCKER AND THEN SPLEETER

 - OS: [e.g. Windows]   USING OS 10.14
 - Ableton version [e.g. 10.1.9] USING 10.0.3
 - Max version [e.g. 8.1.2].     USING 8.0.0

**Comment by diracdeltas** [comment]
This device doesn't support max 8.0, only 8.1 and above. I'm working on a VST version which will.

**Comment by julienneby** [comment]
i downloaded the updated version of Max, is there a way for the device to open up the version i downloaded instead of automatically opening up the 8.0.0 version?

**Comment by diracdeltas** [comment]
i'm not sure, i think you have to configure ableton to use the updated version
