### ISSUE TITLE
Error: Command Failed: Spleeter separate -i

### ISSUE THREAD

**Issue by brvindead** [diracdeltas/spleeter4max#21]
Python is installed, so is ffmpeg. I followed all the instructions for installing, used the command prompts to install spleeter and edited PATHs to include ffmpeg and pip. When I click start in the M4L device, however, I'm given the error message in the title.  Running spleeter as administrator. I attached a photo of the error messages I get in M4L. Any help would be greatly appreciated. Also I donated on bandcamp, it said if I mention that then I might get a faster response.
![Error](https://user-images.githubusercontent.com/65637616/82396664-728fa600-9a1c-11ea-82a1-d048fae42fb7.png)

**Comment by diracdeltas** [comment]
if you open CMD.exe and copy-paste the command from the max console that starts with `spleeter separate -i "D:/..."`, what do you get?

**Comment by diracdeltas** [comment]
if that doesn't help, try https://github.com/diracdeltas/spleeter4max/releases/tag/1.3.1-native instead and it should show a more useful error in the max console

**Comment by codytowstik** [comment]
See this comment, is your output similar?

https://github.com/diracdeltas/spleeter4max/issues/8#issuecomment-632014956

**Comment by brvindead** [comment]
![CMD](https://user-images.githubusercontent.com/65637616/82584643-c6a4a280-9b62-11ea-8c9e-4c61eb7252e5.png)
 This is what CMD looks like when I paste that command into it.

**Comment by brvindead** [comment]
I got it working! ffmpeg wasn't installed correctly.
