### ISSUE TITLE
"newobj node.script: No such object appears" When spleeter.amxd runs

### ISSUE THREAD

**Issue by pinkeminem** [diracdeltas/spleeter4max#25]
**Did you read the installation instructions already?** 
Yes, installed FFmpeg, python 3.7, running spleeter as admin, updated Max for live, running [spleeter native 1.3.1](https://github.com/diracdeltas/spleeter4max/releases/tag/1.3.1-native)

Spleeter -h returns positive results
python check-install.py does not

**Describe the issue**

Spleeter.amxd does not run when object is highlighted

Error code: 

newobj node.script: No such object

I could be just a noob to M4L but it seems like it's not registering the highlighted area. Also do I have to have python running in the background or anything else? 

-Also I'm a noob to programming + scripting but I'm trying to learn so I'm grateful for any additional help :) -

**Max Console Screenshots**
![spleeter issue](https://user-images.githubusercontent.com/65758216/82715821-a69bde80-9c49-11ea-8673-6d7c84016a15.png)

**Info:**
 - Using spleeter or spleeter-native? **Spleet Native**
 - OS: [e.g. Windows] **Windows 10 Home 64-bit**
 - Ableton version [e.g. 10.1.9] **Live 10.0.2**
 - Max version [e.g. 8.1.2] **Max 8.1.3**

**Comment by diracdeltas** [comment]
@pinkeminem nope, python does not need to be running. at a glance, i think the issue might be that you need to be on Live 10.1.x (with Max 8.1.x, which you appear to have).

**Comment by pinkeminem** [comment]
> @pinkeminem nope, python does not need to be running. at a glance, i think the issue might be that you need to be on Live 10.1.x (with Max 8.1.x, which you appear to have).

Ahhh, understood. It said Live 10+ in the requirements so I assumed 1.0 would be fine. Thank you!

**Comment by diracdeltas** [comment]
@pinkeminem i thought it would work as long as max is 8.1 or above, but this is making me think maybe not :/. it's a free update though so i'd be curious if updating fixes it.
