### ISSUE TITLE
Could Not Copy Files From Docker (with latest version)

### ISSUE THREAD

**Issue by ovrdrvn** [diracdeltas/spleeter4max#29]
**Did you read the installation instructions already?** 
If not, read them BEFORE opening an issue. Go to https://github.com/diracdeltas/spleeter4max#before-you-start (spleeter) or https://github.com/diracdeltas/spleeter4max/blob/feature/native-spleeter/README.md#before-you-start (spleeter-native).

**Describe the issue**
I select a whole audio file, click start and it seems to go through the motions but I get the error

**Max Console Screenshots**
Add max console screenshots to help explain your problem. See here for instructions: https://github.com/diracdeltas/spleeter4max#help-its-still-not-working

**Info:**
 - Using spleeter ?
 - OS: Mac OS X 10.15.4
 - Ableton version 10.1.14
 - Max version 8.1.3

**Comment by diracdeltas** [comment]
@ovrdrvn this seems to be the same issue as #26 which i'm stuck on. going to close this as a duplicate. :(

**Comment by diracdeltas** [comment]
sorry i mean https://github.com/diracdeltas/spleeter4max/issues/4
