### ISSUE TITLE
spleeter-native: windows jscript compliation error

### ISSUE THREAD

**Issue by diracdeltas** [diracdeltas/spleeter4max#3]
a few windows users are reporting this error, even though step 3 of https://github.com/diracdeltas/spleeter4max/tree/feature/native-spleeter#windows-steps resolved it for me (windows 10). 

debugging tips:

1. make sure you did step 3 of https://github.com/diracdeltas/spleeter4max/tree/feature/native-spleeter#windows-steps and restart max/ableton after
2. make sure .JS is actually removed by typing  `echo %PATHEXT%` into CMD.exe

**Comment by diracdeltas** [comment]
if anyone here did successfully run spleeter-native on windows, i would love to know if you did this.

IIRC before i changed PATHEXT, i right-clicked on spleeter.js in the spleeter folder and set the default opener for .js files to be Notepad. i don't think that should matter though.

**Comment by soda3x** [comment]
I have this issue and when changing the default opener to Notepad: clicking start in Ableton causes notepad to open and when I close Notepad I get an error saying my audio file was not found in the spleeter directory.

**Comment by soda3x** [comment]
A restart fixes this issue. I will test again to see if changing the default opener matters. It may be worth adding to your readme that a restart is required after removing ".JS" from PATHEXT.

**Comment by diracdeltas** [comment]
@soda3x thanks for the info. i didn't have to restart after changing this but will add it might be required!

**Comment by diracdeltas** [comment]
@soda3x to be clear, did you mean restart your computer or restart ableton/max?

**Comment by soda3x** [comment]
Restart computer.

**Comment by diracdeltas** [comment]
thx, added to the readme
