### ISSUE TITLE
MacOS spleeter-native Error: Illegal Instruction 

### ISSUE THREAD

**Issue by Groovenuts** [diracdeltas/spleeter4max#33]
Hey Legends!

Decided to have a crack at the native version, allthough it was outlined as harder, the part about it running slightly faster than dock version did it for me.

Have minimal experience with coding, zero with python, and first time max user.
Am sure I've done everything right but upon hitting the start button - python quits unexpectedly and I get (the attached screen shot) error message.

**Max Console Screenshots**
![Screen Shot](https://user-images.githubusercontent.com/66618121/84017283-c826f500-a9c1-11ea-8488-2266757773e7.jpg)

**Info:**

After copying and pasting the follwoing into terminal - spleeter separate -i "/Users/imogenjeffreys/Desktop/Yothu Yindi - Treaty (Leftside Wobble Edit).wav" -o "/Users/imogenjeffreys/Downloads/spleeter-native 2" 

I get a text telling me - Illegal instruction: 4

I'm Using -

Spleeter-Native
- Macbook Pro 2010
 - OS 10.15.3
 - Ableton version 10.1.14
 - Max version 8.1.3
 - spleeter path - /usr/local/bin/spleeter
- This is what "pip 3 --version" command shows : pip3 --version
pip 20.0.2 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)

Many thanks!

**Comment by diracdeltas** [comment]
I think this is likely because your Mac is too old to support Tensorflow unfortunately: https://stackoverflow.com/questions/55226284/illegal-instruction-core-dumped-with-tensorflow-1-5 (#9). Sorry!

**Comment by Groovenuts** [comment]
Nooooooooo! Is there nothing I can do? obviously except by a new mac

**Comment by diracdeltas** [comment]
unfortunately i don't think so unless your laptop supports docker :(

**Comment by Groovenuts** [comment]
What about the VST3 Version?

On Jun 12, 2020, at 1:09 PM, yan <notifications@github.com> wrote:

﻿

unfortunately i don't think so unless your laptop supports docker :(

**Comment by diracdeltas** [comment]
it also uses tensorflow so i'm skeptical, but you could try it!
