### ISSUE TITLE
Error: No module named 'numba.decorators' 

### ISSUE THREAD

**Issue by AYAmusic** [diracdeltas/spleeter4max#36]
Hey guys! So I've installed spleeter-native as per the instructions, and I keep getting this error when trying to extract stems:

<img width="853" alt="Screen Shot 2020-06-13 at 12 03 09 PM" src="https://user-images.githubusercontent.com/66884185/84576958-1e0eea80-ad7e-11ea-8a60-42aeec3d7dfb.png">

Does anyone know what's happening? I apologize if this is an obvious error, I'm not very skilled in this area, but I would love to be able to use this natively! ty in advance.

Info:
 - Using spleeter-native
 - OS: Catalina 10.15.5
 - Ableton version 10.1.4
 - Max version 8.1.3

**Comment by gorkemozdemir** [comment]
Somehow it works if you downgrade the numba to a previous version. I keep the same error on current version of numba (0.50).
On the terminal you need to execute: pip3 install numba==0.48.0
Although it might not be a sustainable solution, I hope it helps! 

Yan, I would like to send my gratitudes & a sincere thank you.

**Comment by AYAmusic** [comment]
Gork,

amazing, that fixed it. tysm for the fast response, and yes Yan tysm!

**Comment by diracdeltas** [comment]
thanks all! glad this got fixed without me doing anything. :P

**Comment by duetosymmetry** [comment]
This was fixed in upstream [librosa](https://github.com/librosa/librosa), in their PR [#1107](https://github.com/librosa/librosa/pull/1107). Somebody should ping the librosa devs to update their package on PyPI and conda, and you can require a new minimum version of librosa.
