### ISSUE TITLE
Windows Script Host

### ISSUE THREAD

**Issue by FonzSolo** [diracdeltas/spleeter4max#37]
**Did you read the installation instructions already?** 
If not, read them BEFORE opening an issue. Go to https://github.com/diracdeltas/spleeter4max#before-you-start (spleeter) or https://github.com/diracdeltas/spleeter4max/blob/feature/native-spleeter/README.md#before-you-start (spleeter-native).

**Describe the issue**
A clear description of what problem you are having.
Get this syntax Error after pressing start on the spleeter device.
"Microsoft JScript compilation error"

**Max Console Screenshots**
Add max console screenshots to help explain your problem. See here for instructions: https://github.com/diracdeltas/spleeter4max#help-its-still-not-working

**Info:**
 - Using spleeter or spleeter-native?
 - OS: [Windows 10 Home Version 1909]
 - Ableton version [10.1.14]
![Error](https://user-images.githubusercontent.com/66977712/84714368-73dcc180-af3b-11ea-9737-c7000eeafb2a.jpg)

 - Max version [8.1.4]

**Comment by diracdeltas** [comment]
this is almost always due to step 3 not being done correctly in https://github.com/diracdeltas/spleeter4max/tree/feature/native-spleeter#before-you-start. you may have to reboot after doing it.
