### ISSUE TITLE
noda.script no such object - start button disappears

### ISSUE THREAD

**Issue by mynzcxk** [diracdeltas/spleeter4max#39]
**Did you read the installation instructions already?** 
yes

**Describe the issue**
start button disappears - "noda.script no object found"

**Max Console Screenshots**
<img width="775" alt="Screen Shot 2020-06-18 at 8 13 08 PM" src="https://user-images.githubusercontent.com/67134249/85093109-28771d00-b1a0-11ea-9931-f0b17371680b.png">

**Info:**
 - Using spleeter or spleeter-native? native
 - OS: [e.g. Windows] mac mojave
 - Ableton version [e.g. 10.1.9] 10.05
 - Max version [e.g. 8.1.2] 8

**Comment by diracdeltas** [comment]
sorry, this software isn’t compatible with ableton less than 10.1. this is
mentioned in the instructions.
