### ISSUE TITLE
Unable to Run Ableton 10.1.15 (Standard)

### ISSUE THREAD

**Issue by toadeh** [diracdeltas/spleeter4max#40]
**Did you read the installation instructions already?**  Yes
If not, read them BEFORE opening an issue. Go to https://github.com/diracdeltas/spleeter4max#before-you-start (spleeter) or https://github.com/diracdeltas/spleeter4max/blob/feature/native-spleeter/README.md#before-you-start (spleeter-native).

**Describe the issue**
Added the item to the places, drag it onto an audio channel and it says it's not for this version of Ableton.

"This device is not available in this version of Live"

<img width="477" alt="Screenshot 2020-06-19 at 16 23 23" src="https://user-images.githubusercontent.com/4253680/85149749-94619000-b249-11ea-8835-717be544f05c.png">

However, run it in Suite and it does allow me to drop it on the channel

**Max Console Screenshots**
N/A It doesn't get that far

**Info:**
 - Using spleeter or spleeter-native? spleeter (docker)
 - OS: OSx Catalina 10.15.5
 - Ableton version: 10.1.1.5 (Standard)
 - Max version n/a

**Comment by diracdeltas** [comment]
This is expected cuz Ableton Standard doesn't have Max by default and this is a Max device.
