### ISSUE TITLE
Spleeter Not Working

### ISSUE THREAD

**Issue by FonzSolo** [diracdeltas/spleeter4max#41]
**Did you read the installation instructions already?** 
If not, read them BEFORE opening an issue. Go to https://github.com/diracdeltas/spleeter4max#before-you-start (spleeter) or https://github.com/diracdeltas/spleeter4max/blob/feature/native-spleeter/README.md#before-you-start (spleeter-native).

**Describe the issue**
After clicking the start button I receive this in the output log

node.script: Loaded the spleeter.js script
comment: doesn't understand "bang"
node.script: spleeter separate -i "D:/Muzik/Old Skool/Pop & Rock/80's/Hall & Oates - I Can't Go For That (Radio Edit).mp3" -o "C:\Users\asmed\Desktop\Spleeter\spleeter-native" -p spleeter:4stems-16kHz
js: js: no function set [main.js]
node.script: Error: Command failed: spleeter separate -i "D:/Muzik/Old Skool/Pop & Rock/80's/Hall & Oates - I Can't Go For That (Radio Edit).mp3" -o "C:\Users\asmed\Desktop\Spleeter\spleeter-native" -p spleeter:4stems-16kHz
node.script: Spleeter stderr: 
node.script: Spleeter stdout: 
comment: doesn't understand "spleeterDone"
js: js: no function set [main.js]

**Max Console Screenshots**
Add max console screenshots to help explain your problem. See here for instructions: https://github.com/diracdeltas/spleeter4max#help-its-still-not-working

**Info:**
 - Using spleeter-native?
 - OS: [Windows]
 - Ableton version [e.g. 10.1.15]
 - Max version [8.1.3]

**Comment by diracdeltas** [comment]
Hmm strange that it doesn't say any informative errors. Can you try the following to help with debugging?

1. download https://raw.githubusercontent.com/diracdeltas/spleeter4max/feature/native-spleeter/check-install.py to your home directory
2. open CMD.exe (and change into your home directory if needed)
3. run `python check-install.py` and post the output here

**Comment by FonzSolo** [comment]
Hello.  I have since got spleeter working.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________
