### ISSUE TITLE
Could Not Copy Files From Docker

### ISSUE THREAD

**Issue by ovrdrvn** [diracdeltas/spleeter4max#43]
**Did you read the installation instructions already?** 
If not, read them BEFORE opening an issue. Go to https://github.com/diracdeltas/spleeter4max#before-you-start (spleeter) or https://github.com/diracdeltas/spleeter4max/blob/feature/native-spleeter/README.md#before-you-start (spleeter-native).

**Describe the issue**
Read the material but still no go. Spleeter works on my machine in terminal. ALl files go to "output" Set "output" as a path in Docker prefs just to see...still no go.

**Max Console Screenshots**
Add max console screenshots to help explain your problem. See here for instructions: node.script: Loaded the spleeter.js script
comment: doesn't understand "bang"
js: js: no function set [main.js]
js: js: no function set [main.js]
node.script: docker run --name spleeter -v "/Volumes/STORAGE/ABLETON PACKS/The Forge by Hecq/Samples/Coil Pickup Processed":/input -v "/Users/xxxx/Documents/spleeter/pretrained_models":/model -e MODEL_PATH=/model researchdeezer/spleeter:3.7 separate -i "/input/01_DemonChoir.aif" -o /output -p spleeter:4stems-16kHz
node.script: Spleeter stderr: ERROR:spleeter:An error occurs with ffprobe (see ffprobe output below)

ffprobe version 4.1.4-1~deb10u1 Copyright (c) 2007-2019 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --prefix=/usr --extra-version='1~deb10u1' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
[aiff @ 0x55ec1a0e1ec0] unknown or unsupported codec tag: able is not implemented. Update your FFmpeg version to the newest one from Git. If the problem still occurs, it means that your file has a feature which has not been implemented.
[aiff @ 0x55ec1a0e1ec0] If you wan
node.script: Running docker cp...
node.script: Error running docker cp: Command failed: docker cp spleeter:"/output/01_DemonChoir/" "/Users/xxxxx/Documents/spleeter/01_DemonChoir"
Error: No such container:path: spleeter:/output/01_DemonChoir/
comment: doesn't understand "spleeterDone"
js: js: no function set [main.js]

**Info:**
 - Using spleeter 
OS X Catalina 10.15.5
 - Ableton version 10.1.14
 - Max version bundled with LIve

**Comment by diracdeltas** [comment]
how exactly did you install `ffmpeg` and if you type `ffmpeg` in terminal, what version does it show?

**Comment by ovrdrvn** [comment]
I did the conda install of spleeter 

ffmpeg version 4.2 Copyright (c) 2000-2019 the FFmpeg developers
  built with clang version 4.0.1 (tags/RELEASE_401/final)
  configuration: --prefix=/Users/xxxx/anaconda3 --cc=x86_64-apple-darwin13.4.0-clang --disable-doc --disable-openssl --enable-avresample --enable-gnutls --enable-gpl --enable-hardcoded-tables --enable-libfreetype --enable-libopenh264 --enable-libx264 --enable-pic --enable-pthreads --enable-shared --enable-static --enable-version3 --enable-zlib --enable-libmp3lame
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100

**Comment by ovrdrvn** [comment]
It's the file type. I guess it can't process all types as I put in a .flac and it worked fine. I guess we can close this and I'll research which audio types work...unless you still think this is a bug

**Comment by diracdeltas** [comment]
@ovrdrvn got it. you might be able to get it to process that AIF with ffmpeg 4.3, but not sure. i'll close this for now. thanks!
