### ISSUE TITLE
Spleeter succesfully installed on "EL CAPITAN" !

### ISSUE THREAD

**Issue by mastoppa** [diracdeltas/spleeter4max#47]
Hi i just want to inform that i was able to succesfully install and use spleeter on my macbook (2012) with OSX 10.11.6 El Capitan
I first tried to install with homebrew but that was a nightmare.
Then i tried with Docker , the trick is simply to install the latest Docker version supported by your osx version in my case it was 18.06.1

**Comment by diracdeltas** [comment]
glad to hear it!
