### ISSUE TITLE
"pip3 install spleeter" doesn't work because python installed 3.8 and not 3.7

### ISSUE THREAD

**Issue by oscarhoare13** [diracdeltas/spleeter4max#48]
Doing the native version on a mac. Everything was going well until I used "pip3 install spleeter" (No matching distribution found for spleeter). 

So I tried "python3 -m pip install spleeter" and got the same error. Tried "pip3 --version" and it said I have python 3.8. I don't know why that'd be the case given I followed every other step to get 3.7.

I've never coded in my life, anyone got any hints to either be rid of python 3.8 or to install 3.7 (which spleeter runs on)?

**Comment by oscarhoare13** [comment]
Worked it out. Had 3.8 installed from a while back, changed the pip command to pip3.7 and bam, off it went.

**Comment by diracdeltas** [comment]
@oscarhoare13 i noticed this too. i added a command in the instructions recently to downgrade to 3.7; lmk if that didn't work for you.

**Comment by diracdeltas** [comment]
if you're doing a fresh install: 

```
brew install python@3.7
brew link --force python@3.7
```

if you already installed 3.8, i think you can just do 

```
brew unlink python3
brew install python@3.7
brew switch python 3.7.8
```

**Comment by oscarhoare13** [comment]
thanks for the heads up, got that shit fixed.

new issue lol. i ran it once for a 3 minute song, worked perfectly, took about 1 1/2 mins. yet to have it work again which makes doesn't make much sense. i leave it on, by 20 mins in i opt to restart my computer because everything runs super slow and it doesnt look like the program is finishing. do some songs fare worse than others or is there something to be fixed here?

**Comment by oscarhoare13** [comment]
aaannd worked this one out as well, was running spleeter on uncropped songs from albums so i assume it was doing the whole thing and not the segment i had cut
