### ISSUE TITLE
windows: command failed

### ISSUE THREAD

**Issue by tunonnaemiliana** [diracdeltas/spleeter4max#52]
![culomax](https://user-images.githubusercontent.com/38960595/101546260-d40f6600-39a8-11eb-9c6e-8d12b05d77b6.PNG)

I'm on windows and I am unable to run spleeter-native. 

Spleeter per se seems to be running fine
![spleeter is fine7](https://user-images.githubusercontent.com/38960595/101546385-fd2ff680-39a8-11eb-87c9-88c4793dc869.PNG)

Even check-install.py is not complaining
![superfine](https://user-images.githubusercontent.com/38960595/101546432-120c8a00-39a9-11eb-8f36-249cf5ea7c07.PNG)

And yet:

comment: doesn't understand "bang"
js: js: no function set [main.js]
comment: doesn't understand "spleeterDone"

And i don't know why.
I've tried running it as an administrator: it yielded the same results.

The spleeter-native folder is in documents and i haven't touched it.

**Comment by diracdeltas** [comment]
most of those errors don't actually matter, but the "command failed" line means that max wasn't able to run the spleeter separate command from within node. i'm a little baffled given that it works on the command line. 

just to clarify, are you running both spleeter and max as admin?

https://github.com/diracdeltas/spleeter4max/issues/8#issuecomment-713229985

**Comment by tunonnaemiliana** [comment]
No I'm not. 
Spleeter cli seems to be working fine when run as normal user and as admin.
I've tried doing like #7 said but spleeter-native yielded the same result. Spleeter cli worked fine too, thus I am not running spleeter as an admin anymore :/

**Comment by diracdeltas** [comment]
i think there was some cases where you had to run spleeter.exe as admin for it to work in max, even if it works without admin on the command line.

could you try this:
1. in the spleeter-native folder, open spleeter.js in a text editor
2. replace [this line](https://github.com/diracdeltas/spleeter4max/blob/feature/native-spleeter/spleeter.js#L42) with `const cmd = 'spleeter -h'`
3. restart ableton, try running the device again and post a screenshot of the max console

**Comment by tunonnaemiliana** [comment]
makes sense :)
So i changed [that line](https://github.com/diracdeltas/spleeter4max/blob/feature/native-spleeter/spleeter.js#L42).
Max is now saying that it can't find the file
![weird](https://user-images.githubusercontent.com/38960595/101624348-2046be80-3a1a-11eb-8e09-b4481f22393a.PNG)
but spleeter seems to be working fine
![](https://user-images.githubusercontent.com/38960595/101624345-1fae2800-3a1a-11eb-9cba-c74dda50265c.PNG)

**Comment by diracdeltas** [comment]
cool, so spleeter is indeed callable from Max.

where is the actual file you're trying to separate? in the first screenshot it's in Users/user/Downloads but in the error message it's looking in Documents.

what happens in the command prompt if you cd into the spleeter-native folder, and then run the exact command shown in https://user-images.githubusercontent.com/38960595/101546260-d40f6600-39a8-11eb-9c6e-8d12b05d77b6.PNG ?

**Comment by tunonnaemiliana** [comment]
god i feel so dumb.
Initially `spleeter separate -i "Tom Misch NPR Music Tiny Desk Concert [2020-12-10 003922].wav" -o npr2 -p spleeter:4stems-16kHz` wasn't giving any output.
I tried cutting the audio file and to my surprise it actually worked ![](https://user-images.githubusercontent.com/38960595/101702358-faa0d000-3a80-11eb-80de-bf20bf9c2566.PNG)

After reverting [that line](https://github.com/diracdeltas/spleeter4max/blob/feature/native-spleeter/spleeter.js#L42), the errors are still there, but spleeter-native works nonetheless.

![yoo](https://user-images.githubusercontent.com/38960595/101703234-bdd5d880-3a82-11eb-91cf-2df9e0ae5824.PNG)

god i feel so dumb
**I just had to shorten the audio sample**
jee

**Comment by tunonnaemiliana** [comment]
Still, are those errors supposed to be there?

**Comment by diracdeltas** [comment]
@tunonnaemiliana awesome, glad it worked! yep, those other error messages are not actual errors.

**Comment by tunonnaemiliana** [comment]
yeah, thanks for the help, I'm tipping 5$ on bandcamp :)
Keep it up!
