### ISSUE TITLE
Spleeter install seems to be trying to get an outdated version of tensorflow

### ISSUE THREAD

**Issue by cube-o-sphere** [diracdeltas/spleeter4max#56]
I'm trying to install Spleeter native on macOS. Installation has been going swimmingly, up until hitting this message:

ERROR: Could not find a version that satisfies the requirement tensorflow==2.3.0 (from spleeter) (from versions: 2.5.0rc0, 2.5.0rc1, 2.5.0rc2, 2.5.0rc3, 2.5.0)
ERROR: No matching distribution found for tensorflow==2.3.0

This is a blocker to full installation :(
Any workarounds I might try? Or does this need to be fixed on the dev side?

**Comment by cube-o-sphere** [comment]
Oh I donated today for this also! Since you said to mention it in the thread

**Comment by diracdeltas** [comment]
Hi! What version of python are you using? `python3 --version` should say.

is your MacOS CPU recent enough to support AVX? #9

this looks similar to https://github.com/deezer/spleeter/issues/557

**Comment by cube-o-sphere** [comment]
Thank you for your fast reply! 

I'm using Python 3.9 as it turns out! Which I didn't catch until running that command. I had to unlink it and smooth sailing now. I didn't realize I needed to specify unlink python@3.9 rather than just unlink python3. Thank you :))

**Comment by diracdeltas** [comment]
ah interesting. when i run `brew unlink python3` it shows `Unlinking /usr/local/Cellar/python@3.9/3.9.5... 24 symlinks removed` so i assumed it works for everyone. anyway glad it works now.
