### ISSUE TITLE
11 khz workaround for spleeter4max?

### ISSUE THREAD

**Issue by saturdaysage** [diracdeltas/spleeter4max#62]
As I saw listed on the main repository for spleeter, i see that there is a limit of 11khz range for the model. The wiki says there is a work around for the command line version.

I would like to see a workaround for the spleeter4max version as a producer it would be helpful.

Is there already a solution that i am missing?

Thanks !

<img width="1059" alt="Screen Shot 2022-02-25 at 2 40 49 PM" src="https://user-images.githubusercontent.com/60530552/155799792-93ca25f1-eefc-4fd4-b1c9-d9acde5011cf.png">

**Comment by diracdeltas** [comment]
the latest versions actually go up to 16khz

**Comment by diracdeltas** [comment]
see https://github.com/diracdeltas/spleeter4max/blob/feature/native-spleeter/spleeter.js#L42

**Comment by saturdaysage** [comment]
@diracdeltas awesome, i will try to reinstall and see what i get ! =) [1] 16khz is going to be the limit for now? and [2] does this apply to the docker version as well?

**Comment by diracdeltas** [comment]
yep, latest versions of both docker and native spleeter are on 16khz.
