### ISSUE TITLE
Increase the stems quality

### ISSUE THREAD

**Issue by Kreakx** [diracdeltas/spleeter4max#66]
**Is your feature request related to a problem? Please describe.**
It is possible to increase the final stems quality, cuz actually it's only 128kb/s

**Describe the solution you'd like**
Add the possibility to increase the bit rate please.

I tried to change the valors from 128kb/s by 320kb/s, 1411kb/s but nothing better, maybe it's from the codecs, actually i use  : "type": "unet.softmax_unet", could be possible to fix it with an other codecs pack ?

Thank you for your work, full support :)

**Comment by diracdeltas** [comment]
@Kreakx have you tried https://github.com/diracdeltas/demucs4max ? it's mostly the same but uses demucs under the hood. stem quality is much better.

**Comment by Kreakx** [comment]
Amazing, it works perfectly now, thank you very much :))))
