### ISSUE TITLE
Running spleeter on Windows requires Administrator privileges

### ISSUE THREAD

**Issue by DJUnit27** [diracdeltas/spleeter4max#7]
I've found a possible solution to the Max patch stalling on windows. After installing spleeter-native and testing it on Command Prompt, I realized it required CMD.exe to run as administrator for spleeter to work. Otherwise it would be stuck forever.

The solution I've found is to go to _C:\Program Files\Python37\Scripts_, right click on _spleeter_, select _Properties_, and under _Compatibility_ enable _Run this program as an administrator_.

After doing this, when clicking Run on the Max patch, Windows will prompt asking for admin privileges. After clicking Yes, the script works properly and extracts the stems.

**Info:**
 - spleeter-native
 - OS: Windows 10
 - Ableton version 10.1.13
 - Max version 8.1.1

**Comment by diracdeltas** [comment]
@DJUnit27 thanks a ton for pointing this out! i will add it to the docs.

**Comment by diracdeltas** [comment]
FWIW though, I didn't run into this issue when I tried to install it on Windows 10. I think it probably has to do with how you installed the spleeter python library; if it's installed in such a way that it requires admin priveleges to run, the max patch will also require admin privileges.

**Comment by diracdeltas** [comment]
Also out of curiosity, what error did you see before you changed it to run as admin?

**Comment by DJUnit27** [comment]
> Also out of curiosity, what error did you see before you changed it to run as admin?

It's not giving me an error, it just stays stuck waiting. If I add --verbose to the command, it takes about 10 seconds to start generating output when running as admin, while it never outputs when not run as admin.

**Comment by diracdeltas** [comment]
thanks, closing as this has been added to the spleeter-native instructions
